# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directories:
      - "/"
      - "addon-tools/*"
    schedule:
      interval: "daily"
    labels:
      - "ok-to-test"
      - "dependencies"
    open-pull-requests-limit: 5
    groups:
      k8s:
        patterns: ["k8s.io/*", "sigs.k8s.io/*"]
        update-types: ["major", "minor", "patch"]
      openshift:
        patterns: ["github.com/openshift/*"]
        update-types: ["major", "minor", "patch"]
      other-go-modules:
        patterns: ["*"]
        exclude-patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
          - "github.com/openshift/*"
        update-types: ["major", "minor", "patch"]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
